In [1]:
import numpy as np

In [9]:
np.random.seed(2)
keepprob = 0.5
a3 = np.array([[3., 2., -1.], [1., -2., 4.]])
a3

array([[ 3.,  2., -1.],
       [ 1., -2.,  4.]])

In [10]:
d3 = np.random.rand(a3.shape[0], a3.shape[1]) # rand 함수를 사용하면 각 element의 범위가 0~1사이이다.
d3

array([[0.4359949 , 0.02592623, 0.54966248],
       [0.43532239, 0.4203678 , 0.33033482]])

In [11]:
d3_k = np.random.rand(a3.shape[0], a3.shape[1]) < keepprob # 그 원소들이 0.5보다 작을 확률이 0.5인 원리를 이용한다.
d3_k

array([[ True, False,  True],
       [ True, False, False]])

In [12]:
a3_do = np.multiply(a3, d3) # dropout 진행한 것
a3_do

array([[ 1.30798471,  0.05185246, -0.54966248],
       [ 0.43532239, -0.8407356 ,  1.32133928]])

In [13]:
a3_scale = a3_do / keepprob # dropout으로 인해 output값이 절반(0.5)으로 줄어든 것을 0.5 나누어서 만회한다.(최종출력값이 급격하게 낮으면 안된다.)
a3_scale

array([[ 2.61596941,  0.10370493, -1.09932496],
       [ 0.87064479, -1.68147121,  2.64267857]])

In [14]:
print('a3 ='+ str(a3))
print('d3 ='+ str(d3))
print('d3_k ='+ str(d3_k))
print('\nTrue = 1이고 False = 0입니다.\n')
print('a3_do ='+ str(a3_do))
print('a3_scale' + str(a3_scale))

a3 =[[ 3.  2. -1.]
 [ 1. -2.  4.]]
d3 =[[0.4359949  0.02592623 0.54966248]
 [0.43532239 0.4203678  0.33033482]]
d3_k =[[ True False  True]
 [ True False False]]

True = 1이고 False = 0입니다.

a3_do =[[ 1.30798471  0.05185246 -0.54966248]
 [ 0.43532239 -0.8407356   1.32133928]]
a3_scale[[ 2.61596941  0.10370493 -1.09932496]
 [ 0.87064479 -1.68147121  2.64267857]]
